---
- hosts: ubuntu
  become: yes
  gather_facts:  false
  tasks:
  - name: add jenkins apt-key
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
      state: present
  - name: add jenkins apt repository
    apt_repository:
      repo: ' deb https://pkg.jenkins.io/debian-stable binary/ '
      state: present
      filename: jenkins
      update_cache: yes  
  - name: install jenkins
    apt:
      name: jenkins
      state: present
      update_cache: yes
  - name: start jenkins
    service:
      name: jenkins
      state: restarted
