---
- hosts: redhat
  become: yes
  gather_facts: false
  tasks:
  - name:
    get_url:
      src: http://pkg.jenkins-ci.org/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: add jenkins key
    yum_repository:
      name: jenkins
        baseurl: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        state: present
  - name: install jenkins
    yum:
      name: jenkins
      state: present
  - name: start jenkins
    service:
      name: jenkins
      state: started
